language: node_js
node_js:
  - "10"
cache:
  yarn: true

jobs:
  include:
    - stage: Test
      script: "yarn lint"
      name: "Linting"
    - stage: Build
      script: "yarn build:main"
      name: "Build main process"
      if: branch != master
    - script: "yarn build:render"
      name: "Build renderer"
      if: branch != master
    - script: "yarn electron:dist --win --linux"
      name: "Buid release"
      if: branch = master
