os: osx
osx_image: xcode10.2
language: node_js
node_js: "10"
env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
  yarn: true

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

jobs:
  include:
    - stage: Test
      script: "yarn lint"
      name: "Linting"
    - stage: Build
      script: "yarn build:main"
      name: "Build main process"
      if: branch != master
    - script: "yarn build:render"
      name: "Build renderer"
      if: branch != master
    - script: "yarn electron:dist --win"
      name: "Build release"
      if: branch = master
